[package]
name = "boomslang"
version = "0.1.0"
authors = ["Phil Proctor <philliptproctor@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
futures = "0.1"
log = "0.4"
structopt = "0.2"
serde = "1.0"
serde_yaml = "0.8"
signal-hook = { version = "0.1", features = ["tokio-support"] }
simple_logger = "1.3"
tokio = "0.1"
tokio-fs = "0.1"
tokio-io = "0.1"
tokio-process = "0.2"
